### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by Kikobeats** [rvagg/changelog-maker#3]
```bash
$ changelog-maker --group --start-ref=1.0.0 --end-ref=1.0.1 Kikobeats/acho
/usr/local/lib/node_modules/changelog-maker/commit-stream.js:25
        throw new Error('wut?')
              ^
Error: wut?
    at addLine (/usr/local/lib/node_modules/changelog-maker/commit-stream.js:25:15)
    at DestroyableTransform.onLine [as _transform] (/usr/local/lib/node_modules/changelog-maker/commit-stream.js:54:18)
    at DestroyableTransform.Transform._read (/usr/local/lib/node_modules/changelog-maker/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/usr/local/lib/node_modules/changelog-maker/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/usr/local/lib/node_modules/changelog-maker/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/usr/local/lib/node_modules/changelog-maker/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/usr/local/lib/node_modules/changelog-maker/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/usr/local/lib/node_modules/changelog-maker/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/usr/local/lib/node_modules/changelog-maker/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/usr/local/lib/node_modules/changelog-maker/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
```

and: 

```js
iojs -v
v1.5.1
```

**Comment by rvagg** [comment]
odd, works for me on both OSX and Linux:

```
[/tmp/acho]$ changelog-maker --group --start-ref=1.0.0 --end-ref=1.0.1 Kikobeats/acho
* [[`c9d3998db1`](https://github.com/Kikobeats/acho/io.js/commit/c9d3998db1)] - Merge branch 'master' of github.com:Kikobeats/acho (Kiko Beats)
* [[`7b1f9e8642`](https://github.com/Kikobeats/acho/io.js/commit/7b1f9e8642)] - 1.0.1 releases (Kiko Beats)
* [[`c72b67dd94`](https://github.com/Kikobeats/acho/io.js/commit/c72b67dd94)] - fixed browserify build and little improvements (Kiko Beats)
* [[`76d4b6612f`](https://github.com/Kikobeats/acho/io.js/commit/76d4b6612f)] - Merge pull request #3 from saelfaer/patch-1 (Kiko Beats)
* [[`d703e87d73`](https://github.com/Kikobeats/acho/io.js/commit/d703e87d73)] - Grammar and styling corrections (Sander Houttekier)
* [[`5a37063ceb`](https://github.com/Kikobeats/acho/io.js/commit/5a37063ceb)] - fixed (Kiko Beats)
* [[`775e84aef3`](https://github.com/Kikobeats/acho/io.js/commit/775e84aef3)] - added support for styles (Kiko Beats)
* [[`45f08d63a8`](https://github.com/Kikobeats/acho/io.js/commit/45f08d63a8)] - Update README.md (Kiko Beats)
* [[`2a5d5f7453`](https://github.com/Kikobeats/acho/io.js/commit/2a5d5f7453)] - updated (Kiko Beats)
```

Are there commits that are not pushed to GitHub in this range?

**Comment by Kikobeats** [comment]
hmm happens with whatever repository... I'm trying with this and I have the same error.

In the installation process I have some problems with `peerDependencies`

```bash
npm i -g changelog-maker
npm WARN peerDependencies The peer dependency hyperquest@^0.2.0 included from jsonist will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency stream-browserify@* included from bl will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
/usr/local/bin/changelog-maker -> /usr/local/lib/node_modules/changelog-maker/changelog-maker.js
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires semver@'2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/semver,
npm WARN unmet dependency which is version 4.3.1
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires uid-number@'0.0.5' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/uid-number,
npm WARN unmet dependency which is version 0.0.6
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data requires semver@'2 || 3' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/semver,
npm WARN unmet dependency which is version 4.3.1
npm WARN unmet dependency /usr/local/lib/node_modules/strongloop/node_modules/strong-arc requires loopback-workspace@'^3.5.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/strongloop/node_modules/loopback-workspace,
npm WARN unmet dependency which is version 2.6.0
npm WARN unmet dependency /usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/loopback-workspace/node_modules/loopback requires debug@'~2.0.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/loopback-workspace/node_modules/debug,
npm WARN unmet dependency which is version 1.0.4
npm WARN unmet dependency /usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/loopback-workspace/node_modules/loopback requires inflection@'~1.4.2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/strongloop/node_modules/inflection,
npm WARN unmet dependency which is version 1.6.0
npm WARN unmet dependency /usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/loopback-workspace/node_modules/loopback-datasource-juggler requires debug@'^2.1.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/loopback-workspace/node_modules/debug,
npm WARN unmet dependency which is version 1.0.4
npm WARN unmet dependency /usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/loopback-workspace/node_modules/loopback-explorer/node_modules/express requires debug@'~2.1.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/loopback-workspace/node_modules/debug,
npm WARN unmet dependency which is version 1.0.4
npm WARN unmet dependency /usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/loopback-workspace/node_modules/loopback-explorer/node_modules/swagger-ui requires coffee-script@'~1.6.3' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/coffee-script,
npm WARN unmet dependency which is version 1.9.1
npm WARN unmet dependency /usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/loopback-workspace/node_modules/loopback-explorer/node_modules/swagger-ui requires less@'~1.4.2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/less,
npm WARN unmet dependency which is version 2.4.0
npm WARN unmet dependency /usr/local/lib/node_modules/strongloop/node_modules/strong-pm/node_modules/strong-fork-cicada requires mkdirp@'~0.3.3' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/strongloop/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.5.0
npm WARN unmet dependency /usr/local/lib/node_modules/strongloop/node_modules/strong-pm/node_modules/http-auth/node_modules/htpasswd/node_modules/prompt/node_modules/utile requires async@'~0.2.9' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/strongloop/node_modules/async,
npm WARN unmet dependency which is version 0.9.0
npm WARN unmet dependency /usr/local/lib/node_modules/strongloop/node_modules/strong-pm/node_modules/loopback/node_modules/express requires debug@'~2.1.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/strongloop/node_modules/strong-pm/node_modules/loopback/node_modules/debug,
npm WARN unmet dependency which is version 2.0.0
npm WARN unmet dependency /usr/local/lib/node_modules/strongloop/node_modules/strong-pm/node_modules/loopback/node_modules/loopback-phase requires debug@'^2.1.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/strongloop/node_modules/strong-pm/node_modules/loopback/node_modules/debug,
npm WARN unmet dependency which is version 2.0.0
npm WARN unmet dependency /usr/local/lib/node_modules/strongloop/node_modules/strong-pm/node_modules/loopback-explorer/node_modules/express requires debug@'~2.1.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/strongloop/node_modules/strong-pm/node_modules/loopback-explorer/node_modules/debug,
npm WARN unmet dependency which is version 1.0.4
npm WARN unmet dependency /usr/local/lib/node_modules/strongloop/node_modules/strong-pm/node_modules/loopback-explorer/node_modules/swagger-ui requires coffee-script@'~1.6.3' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/coffee-script,
npm WARN unmet dependency which is version 1.9.1
npm WARN unmet dependency /usr/local/lib/node_modules/strongloop/node_modules/strong-pm/node_modules/loopback-explorer/node_modules/swagger-ui requires less@'~1.4.2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/less,
npm WARN unmet dependency which is version 2.4.0
changelog-maker@1.2.3 /usr/local/lib/node_modules/changelog-maker
├── after@0.8.1
├── minimist@1.1.1
├── split2@0.2.1
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── through2@0.6.3 (xtend@4.0.0, readable-stream@1.0.33)
├── bl@0.9.4 (readable-stream@1.0.33)
├── list-stream@1.0.0 (readable-stream@1.0.33, xtend@2.1.2)
├── ghauth@2.0.0 (mkdirp@0.3.5, xtend@2.1.2, bl@0.7.0, read@1.0.5, stream-browserify@0.1.3, hyperquest@0.2.0)
└── ghissues@0.1.0 (xtend@2.2.0, require-subvert@0.0.3, hyperquest@0.2.0, jsonist@0.0.0)
```

**Comment by rvagg** [comment]
I've just published a new version that should make that peerDependencies warning disappear I think. The rest of the errors are related to npm's bad handling of -g installs where they all get mixed up with each other. You can upgrade to v1.2.4 if you want but I don't think it's necessarily going to help your cause.

What version of git are you using? `git --version`. I'm basing this off git 2.0.0. Also, what does `git log --pretty=full` look like for the project you're using this on? That's the output that's being parsed badly, for some reason the line starting with `commit` isn't being picked up properly.

**Comment by Kikobeats** [comment]
I use git `2.3.0` and doesn't works under `1.2.4`. I have a fresh io installation using `n` as node manager :-(

**Comment by Kikobeats** [comment]
I resolved the unmet erros reinstalling npm, now in `2.7.1` I don't have terminal errors but the library doesn't work. I don't know xD

**Comment by Kikobeats** [comment]
I validate the regex and it's ok: https://www.debuggex.com/r/gqRd-YCb8SkDV_Si

what the hell?

**Comment by Kikobeats** [comment]
GOTO #4
