### ISSUE TITLE
package broken

### ISSUE THREAD

**Issue by guumaster** [rvagg/changelog-maker#6]
I'm getting this error when trying to run `changelog-maker` command: 

```
/usr/lib/node_modules/changelog-maker/changelog-maker.js:75
          console.error(`Error fetching issue #${commit.ghIssue}: ${err.messag
                        ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

**Comment by rvagg** [comment]
See #2, this package is only io.js compatible at the moment because it uses template strings. Feel free to weight in there, we probably need docs on this though!
